### ISSUE TITLE
Nuget package contains 3rd party referenced assembly instead of package reference

### ISSUE THREAD

**Issue by Ross-cz** [gopaycommunity/gopay-dotnet-api#12]
After Nuget install my own referenced Newtonsoft.Json was replaced by GoPay.NET.1.1.7\lib\net45\Newtonsoft.Json.dll. It should use Newtonsoft.Json package reference instead.

**Comment by Leeemons** [comment]
`GoPay.net-sdk.csproj` does not contain dll reference

**Comment by FSichinger** [comment]
outdated, closing this. 1.1.15 is latest version
