### ISSUE TITLE
Missing call to GetAppToken fails with Null reference

### ISSUE THREAD

**Issue by Ross-cz** [gopaycommunity/gopay-dotnet-api#13]
After calling PaymentStatus, this exception occurres:
System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at GoPay.GPConnector.CreateRestRequest(String url, String contentType, Parameter parameter, Method method)\r\n   at GoPay.GPConnector.PaymentStatus(Int64 id)

**Comment by FSichinger** [comment]
Similar as here https://github.com/gopaycommunity/gopay-dotnet-api/issues/11

This is caused by RestSharp client, the client is lacking support for TLS 1.2, it has to be enabled explicitly in `ServicePointManager`
