### ISSUE TITLE
Add .NET 5.0 support (by updating to .NET Standard)

### ISSUE THREAD

**Issue by michaldivis** [gopaycommunity/gopay-dotnet-api#15]
I'd like to ask for .NET 5.0 support for this library by converting it to .NET Standard.

I'm developing a .NET 5.0 app, which is supposed to run on a Linux server and this library is the last .NET Framework dependency, which I'd love to get rid of.

I know the alternative solution is to write my own GoPay client, but I'd prefer to use this one if I can.

Thank you.

**Comment by michaldivis** [comment]
please fix this

**Comment by tomasbohus** [comment]
I need it too.
Thank you

**Comment by FSichinger** [comment]
https://github.com/gopaycommunity/gopay-dotnet-api/pull/14 new version 1.1.15 has been released 
targets .net standard 2.0
