### ISSUE TITLE
Restsharp referencia 105.2.3.0

### ISSUE THREAD

**Issue by TikyConte** [gopaycommunity/gopay-dotnet-api#16]
Dobry den,
nuget ma na pevno referenciu na 105.2.3.0, 
problem nastava nazaciatku pri GPConnector 
pre overenie som vytvoril uplne cisty console app, pridal som len gopay.net nuget, vsetko fungovalo. Stacilo zvysit verziu restsharp o 1 bod hore a projekt hlasy 

[FileLoadException: Could not load file or assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]

**Comment by FSichinger** [comment]
Byla vydana verze 1.1.15
Tato chyba by se jiz nemela vyskytovat, zároveň byl updatován restsharp a ostatní závislosti na poslední dostupné verze
