### ISSUE TITLE
How to get gw_url from BasePayment

### ISSUE THREAD

**Issue by windkitesurf** [gopaycommunity/gopay-dotnet-api#22]
Hi Team, I have below code, I'm able to retrieve token, validity and all of the payment information too except gw_url parameter. Could you please let me know how to get that? In last response.write I would like to call and display that gw_url. Below is my code:

`
using GoPay;
using GoPay.Model.Payment;
using GoPay.Model.Payments;

public partial class Payment : System.Web.UI.Page
{

    // load
    protected void Page_Load(object sender, EventArgs e)
    {
        GoPayConnect();
    }

    protected void GoPayConnect()
    {

        var url = "https://gw.sandbox.gopay.com/api/";
        var clientId = "XXXXXX";
        var clientSecret = "XXXXXXX";

        var connector = new GPConnector(url, clientId, clientSecret);
        connector.GetAppToken();

        Response.Write("Token: " + connector.AccessToken.Token + "<br />");
        Response.Write("TokenType: " + connector.AccessToken.TokenType + "<br />");
        Response.Write("Expire: " + connector.AccessToken.ExpiresIn + "<br />");

        var payment = new BasePayment()
        {
            Currency = GoPay.Common.Currency.EUR,
            Lang = "ENG",
            OrderNumber = "99",
            Amount = 99900,
            Target = new Target()
            {
                GoId = 8392137094,
                Type = Target.TargetType.ACCOUNT
            },
            Callback = new Callback()
            {
                NotificationUrl = "XYZ/paymentconfirmfail.asp",
                ReturnUrl = "XYZ/paymentconfirmsuccess.asp"
            },
            Payer = new Payer()
            {
                Contact = new PayerContact()
                {
                    Email = "test@test.cz"
                },
                DefaultPaymentInstrument = PaymentInstrument.PAYMENT_CARD
            }
        };

        try
        {
            var result = connector.CreatePayment(payment);
        }
        catch (GPClientException e)
        {
            //
        }
        Response.Write("Order No: " + payment.OrderNumber + "<br />");
        Response.Write("Payer: " + payment.Payer + "<br />");
        Response.Write("Amount: " + payment.Amount + "<br />");
        Response.Write("Callback: " + payment.Callback + "<br />");
        Response.Write("Currency: " + payment.Currency + "<br />");
        Response.Write("Target: " + payment.Target + "<br />");
        Response.Write("Url: " + payment.gw_url + "<br />");
    }
}
`

**Comment by standakouba** [comment]
Hi,
I think you have to get the GwUrl from the result. Try this:
`Response.Write("Url: " + result.GwUrl + "<br />");`
