### ISSUE TITLE
Field "payer" not marked as ignorable error

### ISSUE THREAD

**Issue by windkitesurf** [gopaycommunity/gopay-dotnet-api#24]
Hi Team,

I have an issue to create Base payment, according to documentation, field "payer" is not mandatory, nevertheless response from server is: 

**Unrecognized field "Payer" (class cz.gopay.web.api.model.payment.RCreateBasePayment), not marked as ignorable**

This is my BasePayment Jsonbody:

`              {
            Currency = GoPay.Common.Currency.EUR,
            Lang = lang,
            OrderNumber = orderno,
            Amount = payamount,
            Target = new Target()
            {
                GoId = 8392137094,
                Type = Target.TargetType.ACCOUNT
            },
            Callback = new Callback()
            {
                NotificationUrl = "paymentconfirmfail.asp",
                ReturnUrl = "paymentconfirmsuccess.asp"
            },
        };
        try
        {
            var result = connector.CreatePayment(payment);
        }
        catch (GPClientException e)
        {
            //
        }
`

Browser dump of BasePayment with defined variables:
**BasePayment [orderNumber=199, payer=, target=TargetParty [type=ACCOUNT, goId=8392137094], amount=769, currency=EUR, callback=Callback [ returnUrl=paymentconfirmsuccess.asp, notificationUrl=paymentconfirmfail.asp], recurrence=, preAuthorization=False, lang=SK]**

Although I'm not using "Payer" as a field in BasePayment definition, reposnse from server is field "Payer" is not ignorable.

Thanks for your help on this!
Martin

**Comment by standakouba** [comment]
Hi Martin,
Could you please provide us with some additional information?
Are you using the latest SDK version 1.1.19? 
Could you also post part of your source code with the payment creation, connector calls, etc.?

I tried to create the payment without a Payer and it was succesful:
```
        [TestMethod()]
        public void GPConnectorTestCreatePayment2()
        {
            var payment = new BasePayment()
            {
                Currency = Currency.EUR,
                Lang = "SK",
                OrderNumber = "199",
                Amount = 769,
                Target = new Target()
                {
                    GoId = TestUtils.GOID,
                    Type = Target.TargetType.ACCOUNT
                },
                Callback = new Callback()
                {
                    ReturnUrl = @"https://eshop123.cz/return",
                    NotificationUrl = @"https://eshop123.cz/notify"
                },
            };

            var connector = new GPConnector(TestUtils.API_URL, TestUtils.CLIENT_ID, TestUtils.CLIENT_SECRET);
            try
            {
                var result = connector.GetAppToken().CreatePayment(payment);
                Assert.IsNotNull(result);
                Assert.IsNotNull(result.Id);

                Console.WriteLine("Payment id: {0}", result.Id);
                Console.WriteLine("Payment gw_url: {0}", result.GwUrl);
            }
            catch (GPClientException e)
            {
                Console.WriteLine("Create payment ERROR");
                Assert.Fail();
            }
        }
```

Best regards,
Standa

**Comment by windkitesurf** [comment]
Thanks Standa, 

this helps a lot, one more question, with what can I replace

`  
Assert.IsNotNull(result);
Assert.IsNotNull(result.Id);
`
when I am not using [TestMethod()] ?

Thank you again for your help - appreciate!
Martin

**Comment by windkitesurf** [comment]
Hi Standa, 

and to answer your questions:
1. yes, I'm using latest SDK 1.1.19
2. attaching my current code which I'm running currently, and throws Response error at Payer: Unrecognized field "Payer" (class cz.gopay.web.api.model.payment.RCreateBasePayment), not marked as ignorable

[Payment.zip.zip](https://github.com/gopaycommunity/gopay-dotnet-api/files/9762362/Payment.zip.zip)

Thanks again for your help, its highly appreciated!
Martin

**Comment by standakouba** [comment]
Hi Martin,
I tried to fix your code, please take a look at it.

[Payment.aspx.zip](https://github.com/gopaycommunity/gopay-dotnet-api/files/9763996/Payment.aspx.zip)

The first problem was in authorization header, the Bearer keyword was missing. The correct form of this header is:
`Authorization: Bearer {token}`

The second problem was in json serialization, you have to serialize ignoring null fields.

But I don't understand why you use your own rest client. Take a look at GoPayConnect2, all you need is to:
```
// initialize the connector
var connector = new GPConnector(API_URL, CLIENT_ID, CLIENT_SECRET);

// get app token
connector.GetAppToken();

// and create the payment
var resultpaymentcreation = connector.CreatePayment(payment);
```

By the way. **TestMethod** and **Assert** were there because I was running the code as a unit test. You can delete them.

I'm closing this because everything should be clear by now.

Standa

**Comment by windkitesurf** [comment]
Thanks Standa, works now. 
Appreciate your help a lot!
Martin
