### ISSUE TITLE
RestSharp

### ISSUE THREAD

**Issue by TikyConte** [gopaycommunity/gopay-dotnet-api#26]
Dobry den,
musel som nainstalovat najnovsiu verziu restsharp ktoru vyzaduje ina kniznica a ta uz zial nieje kompatibilna s vasou kniznicou.

Ide o drobnu zmenu, ktora sposobuje malu chyb uMethod not found: 'Void RestSharp.RestClient.set_BaseUrl(System.Uri).

Upravit to na novu verziu je uplna malickost, a dokym to nespravite nemozem zasa ja vydat novu verziu nasho eshopu.

Ak by sa dalo prosim cim skor.

**Comment by standakouba** [comment]
Dobry den,
vydali jsme novou verzi 1.1.20, ktera obsahuje update zavislosti na nejnovejsi verzi.
Doufam ze to vyresi vas problem.
