### ISSUE TITLE
RestSharp chyba

### ISSUE THREAD

**Issue by TikyConte** [gopaycommunity/gopay-dotnet-api#27]
Dobry den,
pisal som ohladom novej verzsie restsharp, moc nerozmiem tomu co ste spravil, lebo prabdepodobne ste si znefunkcnil celu kniznicu.

Chyba:  Method not found: 'Void RestSharp.RestClient.set_BaseUrl(System.Uri)'.
Vznika u vas v konstrukto fukncie GPConnector.

Ak ste zvysil zavislost na novej verziu restsharp ale neupravil samotne pouzitie vase DL aktualne nemoze fungovat.

**Comment by standakouba** [comment]
Dobry den,
dekuji za upozorneni. Je upraveno pouziti, vydana nova verze. Doufam ze jiz bude v poradku.
