### ISSUE TITLE
Nuget doesn't contain GoPay dll

### ISSUE THREAD

**Issue by MartinM85** [gopaycommunity/gopay-dotnet-api#3]
Hi,
I've installed the latest NuGet 1.1.0 but I've found out that any reference to GoPay dll has been added. I've also checked downloaded package GoPay.NET.1.1.0.nupkg and it contains only the following dlls:
1. Newtonsoft.Json.dll
2. RestSharp.dll
3. RestSharp.Newtonsoft.Json.dll

**Comment by FSichinger** [comment]
@MartinM85 Fixed in 1.1.3, this version already contains the dll file.
