### ISSUE TITLE
Problém s refundací platby

### ISSUE THREAD

**Issue by vladalas** [gopaycommunity/gopay-dotnet-api#32]
Když se snažím volat funkci na refundaci platby, funkce mi vrací výjimku 111: Wrong value, přičemž tam posílám stejnou částku, kterou mi vrací funkce stav platby (Posílám plnou částka, stav platby mi vrací, že částka je zaplacená pomocí platební karty. Vše dělám na testovacím rozhraní). Můžete mi poradit, v čem je částka špatně?

**Comment by tomved** [comment]
Dobrý den, vaši zprávu obsahující příklad jsme obdrželi také na integrace@gopay.cz, kolega vám na ni odepíše.
Obecně lze říci, že výjimka 111: Wrong value nastává při předávání chybné hodnoty v parametru amount.

**Comment by vladalas** [comment]
Dobrý den, obecně je mi výjimka 111 jasná, nicméně když funkce PaymentStatus vrací "{"id"":3191790420,"state":"PAID","payment_instrument":"PAYMENT_CARD","amount":1000,"currency":"CZK",...  tedy zaplacená platba s částkou 1000, já volám funkci RefundPayment(3191790420, 1000), a dostanu tuto výjimku, nevím, co dělám špatně.

**Comment by tomved** [comment]
3191790420 na částku 10,00 CZK je nyní stále ve stavu PAID - Zaplacena a v rámci simulace na testovacím prostředí lze standardně provést vrácení celé částky. Uveďte prosím kompletní dump requestu refundace, včetně vrácené kompletní odpovědi.

**Comment by vladalas** [comment]
Z knihovny GoPay.net-sdk soubor GPConnector.cs řádek 99 posílám restRequest (serializovaný do json):

{"AlwaysMultipartFormData":false,"MultipartFormQuoteParameters":false,"FormBoundary":null,"Parameters":[{"Name":"Accept","Value":"application/json","Type":2,"Encode":false,"ContentType":null},{"Name":"Content-Type","Value":"application/json","Type":2,"Encode":false,"ContentType":null},{"Name":"Authorization","Value":"Bearer f2JhYctR86aXUrXlSazP+Meu5AtchCf+JthUULTarDGbhh8S+SIqTPosvM2L6S/oGAhCqzTq/FrFt7TnsrTBJv1cnpdZPM+aMwr+v8XBaqM=","Type":2,"Encode":false,"ContentType":null},{"Name":"id","Value":"3191790420","Type":1,"Encode":true,"ContentType":null},{"Name":"amount","Value":"1000","Type":0,"Encode":true,"ContentType":null}],"Files":[],"Method":1,"Timeout":0,"Resource":"/payments/payment/{id}/refund","RequestFormat":0,"RootElement":null,"OnBeforeDeserialization":null,"OnBeforeRequest":null,"OnAfterRequest":null,"Attempts":0,"CompletionOption":0,"ResponseWriter":null,"AdvancedResponseWriter":null}

A obdržený response (serializovaný do json):

{"Data":{"id":0,"result":null,"description":null},"Request":{"AlwaysMultipartFormData":false,"MultipartFormQuoteParameters":false,"FormBoundary":null,"Parameters":[{"Name":"Accept","Value":"application/json","Type":2,"Encode":false,"ContentType":null},{"Name":"Content-Type","Value":"application/json","Type":2,"Encode":false,"ContentType":null},{"Name":"Authorization","Value":"Bearer f2JhYctR86aXUrXlSazP+Meu5AtchCf+JthUULTarDGbhh8S+SIqTPosvM2L6S/oGAhCqzTq/FrFt7TnsrTBJv1cnpdZPM+aMwr+v8XBaqM=","Type":2,"Encode":false,"ContentType":null},{"Name":"id","Value":"3191790420","Type":1,"Encode":true,"ContentType":null},{"Name":"amount","Value":"1000","Type":0,"Encode":true,"ContentType":null}],"Files":[],"Method":1,"Timeout":0,"Resource":"/payments/payment/{id}/refund","RequestFormat":0,"RootElement":null,"OnBeforeDeserialization":null,"OnBeforeRequest":null,"OnAfterRequest":null,"Attempts":1,"CompletionOption
":0,"ResponseWriter":null,"AdvancedResponseWriter":null},"ContentType":"application/json","ContentLength":136,"ContentEncoding":[],"Content":"{\\"date_issued\\":\\"2023-06-05T13:32:37.360+0200\\",\\"errors\\":[{\\"scope\\":\\"G\\",\\"error_code\\":111,\\"error_name\\":\\"INVALID\\",\\"message\\":\\"Wrong value.\\"}]}","StatusCode":409,"IsSuccessStatusCode":false,"IsSuccessful":false,"StatusDescription":"Conflict","RawBytes":"eyJkYXRlX2lzc3VlZCI6IjIwMjMtMDYtMDVUMTM6MzI6MzcuMzYwKzAyMDAiLCJlcnJvcnMiOlt7InNjb3BlIjoiRyIsImVycm9yX2NvZGUiOjExMSwiZXJyb3JfbmFtZSI6IklOVkFMSUQiLCJtZXNzYWdlIjoiV3JvbmcgdmFsdWUuIn1dfQ==","ResponseUri":"https://gw.sandbox.gopay.com/api/payments/payment/3191790420/refund","Server":"Apache","Cookies":[{"Comment":"","CommentUri":null,"HttpOnly":true,"Discard":false,"Domain":"gw.sandbox.gopay.com","Expired":false,"Expires":"0001-01-01T00:00:00","Name":"JSESSIONID","Path":"/","Port":"","Secure":true,"T
imeStamp":"2023-06-05T13:28:50.8474458+02:00","Value":"0eQ9zOfoocdcCN3MhHROPAZWZ6IVNeevLr4Romap.app1.intgr","Version":0}],"Headers":[{"Name":"Connection","Value":"keep-alive","Type":2,"Encode":false,"ContentType":null},{"Name":"Strict-Transport-Security","Value":"max-age=15552000; includeSubDomains; preload","Type":2,"Encode":false,"ContentType":null},{"Name":"X-XSS-Protection","Value":"1; mode=block","Type":2,"Encode":false,"ContentType":null},{"Name":"X-Content-Type-Options","Value":"nosniff","Type":2,"Encode":false,"ContentType":null},{"Name":"X-Frame-Options","Value":"SAMEORIGIN","Type":2,"Encode":false,"ContentType":null},{"Name":"Cache-Control","Value":"no-store, must-revalidate, no-cache","Type":2,"Encode":false,"ContentType":null},{"Name":"Date","Value":"Mon, 05 Jun 2023 11:32:37 GMT","Type":2,"Encode":false,"ContentType":null},{"Name":"Server","Value":"Apache","Type":2,"Encode":fals
e,"ContentType":null}],"ContentHeaders":[{"Name":"Content-Length","Value":"136","Type":2,"Encode":false,"ContentType":null},{"Name":"Content-Type","Value":"application/json","Type":2,"Encode":false,"ContentType":null}],"ResponseStatus":2,"ErrorMessage":null,"ErrorException":{"ClassName":"System.Net.Http.HttpRequestException","Message":"Request failed with status code Conflict","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":null,"RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233088,"Source":null,"WatsonBuckets":null,"SafeSerializationManager":{"m_serializedStates":[{}]},"CLR_SafeSerializationManager_RealType":"System.Net.Http.HttpRequestException, System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"},"Version":null,"RootElement":null}

**Comment by standakouba** [comment]
Dobrý den, vyzkoušejte prosím verzi 1.2.4
Měla by vyřešit oba problémy, tedy jak refund tak dotaz na stav platby.

**Comment by vladalas** [comment]
Dobrý den, 
verze 1.2.4 mi vrací zcela stejné výjimky jako předchozí verze (jak funkce pro refundaci, tak funkce pro stav platby).

**Comment by vladalas** [comment]
Dobrý den, vyzkoušel jsem verzi 1.2.4. Když si ji stáhnu pomocí NuGet, vrací mi stejné chyby jako předchozí verze. Když si kód stáhnu přímo z GitHubu a připojím projekt napřímo, tak funkce fungují. Není možné, že došlo k nějaké chybě při publish do NuGet?

**Comment by vladalas** [comment]
Dobrý den, verze 1.2.5 již funguje bez problémů.
