### ISSUE TITLE
Předvybrání platebních metod jako "Moje platba KB"

### ISSUE THREAD

**Issue by ErikMatuska** [gopaycommunity/gopay-dotnet-api#37]
Dobrý den,

klient by chtěl zobrazit na eshopu více možností platby, které má povolené v GoPay

Aktuální verze nabízí pouze
`public enum PaymentInstrument
{
    PAYMENT_CARD,
    BANK_ACCOUNT,
    PRSMS,
    MPAYMENT,
    COUPON,
    PAYSAFECARD,
    SUPERCASH,
    GOPAY,
    PAYPAL,
    BITCOIN,
    MASTERPASS,
    ACCOUNT,
    GPAY,
    APPLE_PAY,
    CLICK_TO_PAY,
    TWISTO,
    SKIPPAY,
    UNKNOWN
}`

GitHub: https://github.com/gopaycommunity/gopay-dotnet-api/blob/master/GoPay.net-sdk/src/Model/Payment/PaymentInstrument.cs
Dokumentace také: https://doc.gopay.cz/#payment-instrument

Klient by chtěl například zobrazit 
![screenshot-1](https://github.com/user-attachments/assets/56fab42d-786d-400e-9ca8-7a4977aff2a8)

Pole DefaultPaymentInstrument a AllowedPaymentInstruments již známe a používáme třeba pro Google Pay, nevidíme zde ale tyto možnosti.
Otázka tedy je: **podporuje API tyto možnosti, pokud ano, proč nejsou v SDK nebo oficiální dokumentaci?** 

(Původně jsem dotaz vznesl na podporu, ta mě přesměrovala sem)

**Comment by gopayprovoz** [comment]
Dobrý den,
ano, jednotlivé banky lze v košíku zobrazit. Záleží na variantě předávání, kterou zvolíte a jak se mají banky na bráně zobrazit. Parametrem allowed_swifts můžete v poli payer (https://doc.gopay.cz/#payer) upřesnit povolené banky pro online a PSD2 bankovní přeovdy (dle číselníku: https://doc.gopay.cz/#swift) a parameterm default_swift konkrétní předvybranou. Možnosti zobrazení jsou popsané v [následující části dokumentace: https://doc.gopay.cz/#urceni-platebnich-metod__P%C5%99edvybran%C3%A1%20platebn%C3%AD%20metoda
Záleží, zda-li chcete z košíku rovnou směrovat na konkrétní banku, anebo na platební bráně zobrazit příslušnou banku coby top v nabídce bank.

Přikládám ukázku s polem předávaným u platby v .NETu.

![image](https://github.com/user-attachments/assets/af9b87eb-f09e-49db-8147-1303469f50ad)
