### ISSUE TITLE
Cannot install nuget package

### ISSUE THREAD

**Issue by florimond-gaming1** [gopaycommunity/gopay-dotnet-api#5]
> Install-Package : Could not install package 'GoPay.NET 1.1.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly 
> references or content files that are compatible with that framework. For more information, contact the package author.
> At line:1 char:1
> + Install-Package GOPAY.NET
> + ~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

Using VS2013

**Comment by FSichinger** [comment]
The minimal required .NET version which we support is 4.5.2.

**Comment by florimond-gaming1** [comment]
Ok, I see you've just modified the documentation to reflect this fact.
Beside the framework version, what's also an issue for us is the dependency on Newtonsoft.Json 9 (all our projects use .net 4.5 and Json 6).

I've decided to try using you api in version 1.1.2, which works with .net 4.5. However, this package won't add the reference automatically in my project. I had to add the reference myself, by selecting the dll in the debug folder.

**Comment by florimond-gaming1** [comment]
It's actually worse than that. Even though I added the dll manually, and that the namespaces are recognized by intellisense, the solution doesn't build ("The type or namespace "GoPay" could not be found").

Also, it seems that the namespaces are different in the Debug dll and in the Release dll !

**Comment by FSichinger** [comment]
>Beside the framework version, what's also an issue for us is the dependency on Newtonsoft.Json 9 (all our projects use .net 4.5 and Json 6).

I see, the version 4.5.2 is here only due to the dependencies. I'll try to downgrade minimal required version of newtonsoft.json. 

>It's actually worse than that. Even though I added the dll manually, and that the namespaces are recognized by intellisense, the solution doesn't build ("The type or namespace "GoPay" could not be found").

I just manually installed 1.1.4 version on mono-develop solution, everything is working fine. At this point i'm not really sure whats the problem.

**Comment by florimond-gaming1** [comment]
> I just manually installed 1.1.4 version on mono-develop solution, everything is working fine. At this point i'm not really sure whats the problem.

I believe you, but the 1.1.4 is already not compatible with 4.5 anymore. The version I tried to install was the 1.1.2.

**Comment by FSichinger** [comment]
Fixed in https://github.com/gopaycommunity/gopay-dotnet-api/pull/6, version 1.1.5 released
